export const channel = {
  store: {
    getSettings: "settings:get",
    setSettings: "settings:set",
    clearSettings: "settings:clear",
    get: "store:get",
    set: "store:set",
    clear: "store:clear",
  },
  dialog: {
    selectDirectory: "dialog:select-directory",
    showFileInFolder: "dialog:show-file-in-folder",
    selectFile: "dialog:select-file",
    selectImages: "dialog:select-images",
    openDirectory: "dialog:open-directory",
    openExternal: "dialog:open-external",
  },
  font: {
    getFonts: "font:get-fonts",
  },
  file: {
    getSize: "file:get-size",
  },
  download: {
    getList: "download:get-list",
    getDownloadData: "download:get-download-data",
    add: "download:add",
    addList: "download:add-list",
    pause: "download:pause",
    resume: "download:resume",
    cancel: "download:cancel",
    retry: "download:retry",
    sync: "download:sync",
    clear: "download:clear",
  },
  lyrics: {
    searchNeteaseSongs: "lyrics:netease-search",
    getNeteaseLyrics: "lyrics:netease-lyrics",
    searchLrclib: "lyrics:lrclib-search",
    syncWithWhisperXStart: "lyrics:sync-whisperx-start",
    syncWithWhisperXProgress: "lyrics:sync-whisperx-progress",
    syncWithWhisperXDone: "lyrics:sync-whisperx-done",
    checkWhisperXDeps: "lyrics:check-whisperx-deps",
    installWhisperXDeps: "lyrics:install-whisperx-deps",
  },
  router: {
    navigate: "router:navigate",
  },
  http: {
    get: "http:get",
    post: "http:post",
  },
  player: {
    state: "player:state",
    prev: "player:prev",
    next: "player:next",
    toggle: "player:toggle",
  },
  shortcut: {
    triggered: "shortcut:triggered",
    register: "shortcut:register",
    unregister: "shortcut:unregister",
    registerAll: "shortcut:register-all",
    unregisterAll: "shortcut:unregister-all",
  },
  app: {
    getVersion: "app:get-version",
    checkUpdate: "app:check-update",
    onUpdateAvailable: "app:on-update-available",
    downloadUpdate: "app:download-update",
    updateMessage: "app:update-message",
    quitAndInstall: "app:quit-and-install",
    openInstallerDirectory: "app:open-installer-directory",
    onBeforeQuit: "app:on-before-quit",
    isDev: "app:is-dev",
    setProxySettings: "app:set-proxy-settings",
  },
  cookie: {
    get: "cookie:get",
    set: "cookie:set",
  },
  localMusic: {
    scan: "local-music:scan",
    deleteFile: "local-music:delete-file",
  },
  shazam: {
    recognize: "shazam:recognize",
    getDesktopSources: "shazam:get-desktop-sources",
    requestMicPermission: "shazam:request-mic-permission",
  },
  fancyPlayer: {
    peekThumb: "fancy-player:peek-thumb",
    readSourceFile: "fancy-player:read-source-file",
    saveThumb: "fancy-player:save-thumb",
    removeThumb: "fancy-player:remove-thumb",
  },
  window: {
    toggleMini: "window:toggle-mini",
    minimize: "window:minimize",
    toggleMaximize: "window:toggle-maximize",
    close: "window:close",
    maximize: "window:maximize",
    unmaximize: "window:unmaximize",
    isMaximized: "window:is-maximized",
    enterFullScreen: "window:enter-full-screen",
    leaveFullScreen: "window:leave-full-screen",
    isFullScreen: "window:is-full-screen",
    toggleDevTools: "window:toggle-dev-tools",
    toggleDesktopLyrics: "window:toggle-desktop-lyrics",
    desktopLyricsVisibilityChanged: "window:desktop-lyrics-visibility-changed",
    desktopLyricsSetIgnoreMouseEvents: "window:desktop-lyrics-set-ignore-mouse-events",
    desktopLyricsGetBounds: "window:desktop-lyrics-get-bounds",
    desktopLyricsSetBounds: "window:desktop-lyrics-set-bounds",
  },
};
